### ISSUE TITLE
TextToGcode library returning none...

### ISSUE THREAD

**Issue by hyderjatt** [Yoyolick/TextToGcode#3]
Hello,

I am trying to convert text to Gcode using TextToGcode library. It is returning none.

![image](https://user-images.githubusercontent.com/103831095/194693397-b8d7d3c5-e817-4568-b5b9-8ef335b55242.png)

I have attached a screenshot. Please let me know if I am doing anything wrong.

**Comment by Yoyolick** [comment]
I was able to replicate your issue, and it really is just an oversight on my part. If you use "return" lowercase it will work.

`from ttgLib.TextToGcode import ttg`

`gcode = ttg("ryan",1,0,"return",1).toGcode("M02 S500","M05 S0","G0","G1")`

`print(type(gcode))`
gives:
`<class 'list'>`

<img width="854" alt="Screen Shot 2022-10-08 at 11 03 25 AM" src="https://user-images.githubusercontent.com/43967290/194714050-ad729b76-6f97-43f6-a114-0364edc2c01f.png">

I will do some work soon to clean up parts of the library that do not work as expected, I made this library quite a while ago and it is definitely in need of rework. Please do not hesitate to let me know if you find anything else that you believe needs changing or if you run into any problems.

**Comment by zoogies** [comment]
This should have been fixed completely with f11f46a. Please reach out if you have any other issues! 😃
